### ISSUE TITLE
Server Error bei logout, wenn auf logout geklickt wird

### ISSUE THREAD

**Issue by sven212** [SWP2-2018/swp2-2018#32]
### Versionshinweise
#25 Version 1.0 auf internen Releaseserver

### Schritte zu Reproduzieren
1. Ausloggen
2. In der Logoutansicht links oben auf logout klicken

### Was sollte passieren
Sollte ausgeloggt werden, ohne Fehler produzieren zu können

### Was wirklich passiert
Errorseite wird angezeigt

**Comment by Milkdrinker** [comment]
siehe commits für #37.
Beim Logout gibt es keine extra Seite mehr.
