### ISSUE TITLE
Ausbilder: Passwort Erneuern Error

### ISSUE THREAD

**Issue by Wagabuga** [SWP2-2018/swp2-2018#33]
**Versionshinweise**

#25 Version 1.0 auf internen Releaseserver

**Schritte zu Reproduzieren**

1. Als Ausbilder einloggen
2. Bericht öffnen (editReport.jsp)
3. Passwort erneuern
4. Neues gewünschtes Passwort eingeben und bestätigen

**Was sollte passieren**

Das eingegeben Passwort sollte in die Datenbank übernommen werden, und die selbe Seite bleibt bestehend

**Was wirklich passiert**

Server Status 500 - Internal Server Error

**Comment by Breitkrug** [comment]
siehe #51
