### ISSUE TITLE
Farben für Berichte definieren und implementieren

### ISSUE THREAD

**Issue by sven212** [SWP2-2018/swp2-2018#34]
Farben definieren, .z.b. in der Wiki oder hier. Und entsprechend einbauen.

**Comment by Milkdrinker** [comment]
BerichtStatus
0: Wird nicht angezeigt
1: Azubi: blau
2: Azubi: gelb
Ausbilder: blau
3:Azubi: rot
Ausbilder: rot
4:Azubi: grün

siehe auch #56
