### ISSUE TITLE
Saubere Darstellung von Ä,Ö,Ü(ä, ö, ü) auf den Seiten und der Datenbank

### ISSUE THREAD

**Issue by Breitkrug** [SWP2-2018/swp2-2018#42]

**Comment by Wagabuga** [comment]
**Umlaute im Namen, bei einem Ausgewähltem Bericht werden weiterhin nicht korrekt angezeigt.**

Bin folgendermaßen vorgegangen:

Als Ausbilder eingeloggt (cmohr@www.de)

Offene Berichte anwählen

Bericht von Hofmann-Böhme auswählen
Name wird nicht korrekt dargestellt
