### ISSUE TITLE
navbar automatisch zuklappen

### ISSUE THREAD

**Issue by ganandoor56** [SWP2-2018/swp2-2018#46]
**Versionshinweise**
#25 Version 1.0 auf internen Releaseserver

**Schritte zu Reproduzieren**
1. Als Smartphone-Ansicht darstellen (zB Galaxy S5)
2. navbar Leistensymbol anklicken.
3. Dropdownmenü wird hier angezeigt.

**Was sollte passieren**
Bei out of focus sollte es wieder zuklappen. Das nimmt fast die Hälfte des Bildschirms weg.

**Was wirklich passiert**
 > zB Übersichtsseite: Beim Klick auf "Offene Berichte" sollte das Dropdownfenster wieder zuklappen

**Comment by Milkdrinker** [comment]
@ganandoor56 kannst es bitte nochmal genauer beschreiben? 
Bei out of focus geht die navbar nicht zu wie beschrieben. 
Doch wenn man eine andere Seite über die navbar aufruft(klickt) klappt die navbar wieder zu.

**Comment by Milkdrinker** [comment]
Nachdem ich jetzt drei Stunden vergeblich versucht habe die navbar bei "out of focus" zuklappen zu lassen wird dieser bug geclosed. Es ist nicht erforderlich und auf anderen bekannten wie Microsoft und w3schools ist es genauso.
