### ISSUE TITLE
Registrierung: Ausbilder; Zu viele Felder, Ausbilder ID kann zu Fehler führen

### ISSUE THREAD

**Issue by ganandoor56** [SWP2-2018/swp2-2018#53]
**Versionshinweise**
#25 Version 1.0 auf internen Releaseserver

**Schritte zu Reproduzieren**
...

**Was sollte passieren**
Ausbilder wird angelegt

**Was wirklich passiert**
- Muss der Ausbilder seinen Beruf angeben?
- Der Ausbilder braucht das Feld Ausbildungsjahr nicht.
- !!! AusbilderID. Die ID kann man nicht frei wählen. z.B. 1 Wird akzeptiert (auf der DB-Tabelle bekommt es jedoch einen anderen Wert), aber 300 führt zu einer Fehlermeldung.
... Vielleicht sollte man sich da noch etwas dazu überlegen.

>> Error, please try again later.

Funktion: "Ich bin kein Roboter" einbauen?

**Comment by Milkdrinker** [comment]
siehe #41
