### ISSUE TITLE
Mobil-Ansicht: Anmelde-View zeigt im Mobilformat den Reiterbutton oben rechts an

### ISSUE THREAD

**Issue by KaaniBoi** [SWP2-2018/swp2-2018#72]
**localhost/login.jsp:**

- 3-fach-gestrichelter Reiterbutton **oben rechts** in der blauen Leiste ist zwar da, aber hat **keine** Funktion.

**Comment by Wagabuga** [comment]
Issue wird aus unwichtigkeit Ignoriert
